### ISSUE TITLE
FYI: Ringing the bell for ablog

### ISSUE THREAD

**Issue by marble** [abakan/ablog#23]
Hi Ahmet,
this is just to let you know, that I'm trying to spread the news about ablog: http://mbless.de/blog/2014/11/19/basic-installation-of-sphinx-and-ablog.html
I'm thankful every day for your ablog!

**Comment by abakan** [comment]
Hey, ablog now has a [quick start guide](http://ablog.readthedocs.org/manual/ablog-quick-start/) and [build/serve commands](http://ablog.readthedocs.org/manual/ablog-commands/). You should check them out and let me know what you think :)

**Comment by marble** [comment]
Thanks for letting me know! I feel very connected to you and your work and heavily depend on ablog, though I'm using a version that has patches here and there. I'm using my blog every day for daily notes while I'm doing (mostly TYPO3) webwork. At some point I'll rework my collection of tools. That'll be the moment I'll investiagte what you've added. Til then I just keep recommending ablog as blogging solution :-)
