### ISSUE TITLE
It would be useful if you could include pages generated by ablog in the Sphinx toctree

### ISSUE THREAD

**Issue by moorepants** [abakan/ablog#30]
I'd like to have a link to the blog page appear in the toctree, but I can't figure out how to do it. Is this possible?

**Comment by abakan** [comment]
I don't know of a way of doing that, but maybe you could use ``` :ref:`blog-posts` ``` to link to blog page right after `toctree` directive.

**Comment by abakan** [comment]
All right, I figured how to do this. Add `Title <http://yoursite.com/blog>` to any toctree, e,g.
```
.. toctree::

   Blog Posts <http://ablog.readthedocs.org/blog/>
```
