### ISSUE TITLE
Feature request: add excerpts to post lists

### ISSUE THREAD

**Issue by moorepants** [abakan/ablog#31]
I'd really like to embed the list of blog posts with excerpts into a rst page. It would be great if the post list directive let you specify an excerpt style so that you get more than just a list.

**Comment by abakan** [comment]
That would be a nice feature to have. In fact, a `blog.rst` file could then replace the HTML page that is generated by ablog. That would also allow for including blog page in toctree. I will see how much work this involves in a few days.

**Comment by moorepants** [comment]
I can possibly hack at this too. I'm not familiar with writing Sphinx extensions or your codebase. If you can give me a lead on where to start, I can play around with the idea in my spare time too.

**Comment by abakan** [comment]
Hey, I have been working on releasing v0.5, but totally forgot to attend these issues. I have just made changes to add excerpts to post lists and made another release. Sorry for the delay on this.

**Comment by moorepants** [comment]
Awesome. Thanks for doing that. I'll try it out soon.
