### ISSUE TITLE
Postlist, excerpts and post command enhancements

### ISSUE THREAD

**Issue by ketanbhatt** [abakan/ablog#35]
Add option to disable bullet style listing of PostList (sometimes I just want to show my certain posts but without a list!)

Excerpts should end with ellipses.

"ablog post hello-world" should by default make a new file hello-world with a .rst extension, and with the title of the new post as Hello World, that is, the file name. Right now it is just New Post. (Why? Because it is a better experience)

Just suggestions. Wonderful tool already, and I like python. If you don't have time for implementing this, I can try doing it if you like.

**Comment by abakan** [comment]
* No bullets in post lists by default (I thought it will look better).
* `ablog post` is also enhanced.
* Ellipses also sound good, but I will think about the best way to incorporate it.
