### ISSUE TITLE
Cross Referencing fails if used in first paragraph (after the title) of the post

### ISSUE THREAD

**Issue by mementum** [abakan/ablog#41]
If an RST page is marked with .. post::, using any cross-referencing syntax in the first paragraph of the post will produce an exception during the build process.

Error message (the relevant part): "NotImplementedError: Unknown node: pending_xref"

If the reference is used

Tested with sphinx 1.2 and 1.3.x

**Comment by abakan** [comment]
Release a fix. Thanks for reporting the issue.

**Comment by mementum** [comment]
A lot more thanks for fixing it
