### ISSUE TITLE
Not in Latin tags do not work

### ISSUE THREAD

**Issue by uralbash** [abakan/ablog#45]
For example tag ``Жириновский``, when calling ``tag.docname`` it return empty string. I think problem in this line https://github.com/abakan/ablog/blob/master/ablog/blog.py#L34

```python

 string = re.sub(r'[^\w\s-]', '', string).strip().lower()
```

**Comment by abakan** [comment]
Your example tag worked fine with Python 3. In Python 2, I pass `re.UNICODE` flag to `re.sub` function. This should resolve the issue.

**Comment by uralbash** [comment]
It works, thanks
