### ISSUE TITLE
ablog deploy fails on windows

### ISSUE THREAD

**Issue by montyvesselinov** [abakan/ablog#46]
Please let me know how to resolve the issue.

Python complains that needs overwrite existing files.

**Comment by abakan** [comment]
Can you copy screen output here?

**Comment by montyvesselinov** [comment]
I made the following change to make it work. The other option is check for file existence and delete before renaming. Hope this helps.

        for tm in tomove:
            for root, dirnames, filenames in os.walk(website):
                for filename in filenames:
                    fn = os.path.join(root, filename)
                    fnnew = fn.replace(website, gitdir)
                    try:
                        os.renames(fn, fnnew)
                    except WindowsError:
                        os.remove(fn)
                        os.renames(fn, fnnew)
                    git_add.append(fnnew)
        print('Moved {} files to {}.github.io'
            .format(len(git_add), github_pages))

**Comment by abakan** [comment]
Yes, that helped.
