### ISSUE TITLE
Breaks on JSON builds

### ISSUE THREAD

**Issue by ericholscher** [abakan/ablog#47]
Having an issue with updating our blog because ablog is breaking when built with the Sphinx JSON backend. You can see this here: 

https://readthedocs.org/projects/readthedocs-blog/builds/3323603/

It appears that the logic here is quite naive: https://github.com/abakan/ablog/blob/master/ablog/post.py#L340 -- I wish there was a better way to say that a Sphinx backend builder generates HTML. This should really be an attribute on the builder, instead of a hueristic on the builder name. Perhaps we should add this to Sphinx.

**Comment by ericholscher** [comment]
Went ahead and opened this: https://github.com/sphinx-doc/sphinx/issues/2038

**Comment by abakan** [comment]
Thanks for reporting this. After above commit, JSON builder works fine. But the build does include archive pages, and other pages do not contain blog related links. If you are familiar with literature explaining how these JSON builds are used, could you point me to that so I can improve handling of blog features with JSON builder?

**Comment by ericholscher** [comment]
Is there a reason you're using the build name instead of the builder format? https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L69

**Comment by abakan** [comment]
No, I wasn't aware of format attribute. But, if I use that I won't be able to avoid JSON builder.

**Comment by ericholscher** [comment]
Hmm. My worry is that the RTD builders don't have the specific names as used by the default sphinx: https://github.com/rtfd/readthedocs-sphinx-ext/blob/master/readthedocs_ext/readthedocs.py#L129 -- which will break on this logic I think.

**Comment by abakan** [comment]
I see. I could do `format == 'html' and name not in {'json', 'pickle'}`, and make a release soon.
