### ISSUE TITLE
Any thoughts to allowing alternate Jinja2 templates?

### ISSUE THREAD

**Issue by pauleveritt** [abakan/ablog#48]
I'm interested in doing an alternate template, but I fear this will mean essentially forking ABlog. Any plans for a configuration option or plugin approach to use external packages for a template?

**Comment by abakan** [comment]
Yes, we could allow alternate templates. Are there Sphinx themes using other template engines? I am not familiar with other options.

**Comment by uralbash** [comment]
Here's an example that uses Mako https://bitbucket.org/zzzeek/zzzeeksphinx/

**Comment by pauleveritt** [comment]
> On Sep 24, 2015, at 8:42 PM, Ahmet Bakan <notifications@github.com> wrote:
> 
> Yes, we could allow alternate templates. Are there Sphinx themes using other template engines? I am not familiar with other options.
> 
You are right that my question was perhaps phrased poorly by saying Jinja2. However, leaving Jinja2 might mean a more difficult abstraction, more like a full plug-in architecture. By staying with Jinja2, it’s more like replacement of base templates.

Perhaps you can rely on Sphinx’s pluggability for the theme component.

—Paul

**Comment by abakan** [comment]
Paul,
Yes, we should rely on Sphinx for theme/template component. To support mako, I will work on translating `ablog/templates/*.html` to `ablog/templates/*.mako` files. We could include files to support any other template engine as well.
Ahmet

P.S. Sorry for delayed responses, there is a newborn at home :)

**Comment by abakan** [comment]
Ok, I tried to add `.mako` templates, but I didn't like how that works. I am giving up, and closing this issue. If you wanna pursue that you are welcome to use template in mako branch.

**Comment by pauleveritt** [comment]
That's fine, I didn't expect "Support Mako" to be part of this. If make ABlog look different is really a Sphinx theme customization issue, then closing this is certainly the right thing.

**Comment by abakan** [comment]
I would love if someone makes a theme to look blogs different than documentation pages. I am cleaning up and documenting ablog API to encourage that person :)

**Comment by uralbash** [comment]
@abakan I use Ablog and my own theme for http://uralbash.ru/

**Comment by pauleveritt** [comment]
Was there any ABlog-unique work to it, or was it just normal Sphinx theming?

—Paul

**Comment by uralbash** [comment]
@pauleveritt I just redefined ``index.rst`` (https://github.com/uralbash/blog/blob/master/index.rst) and ``post.html`` (https://github.com/uralbash/blog/blob/master/_templates/page.html)

Also added ``_templates`` dir in ``conf.py`` (https://github.com/uralbash/blog/blob/master/conf.py#L233)
```python
templates_path = ['_templates', ablog.get_html_templates_path()]
```
In general it's a standard sphinx theme.
