### ISSUE TITLE
Use Font-Awesome Icon in Content?

### ISSUE THREAD

**Issue by nfarrar** [abakan/ablog#49]
Is there a way to use the font-awesome icons in post or page content?

**Comment by abakan** [comment]
Not an ideal way, but you could use `raw` directive, e.g.

```html
.. raw:: html

   <ul class="fa-ul">
     <li><i class="fa-li fa fa-check-square"></i>List icons</li>
     <li><i class="fa-li fa fa-check-square"></i>can be used</li>
     <li><i class="fa-li fa fa-spinner fa-spin"></i>as bullets</li>
     <li><i class="fa-li fa fa-square"></i>in lists</li>
   </ul>
```

What kind of use cases are you interested in? `raw` would not work to insert an icon in the middle of a paragraph. I was thinking of adding an inline role for that but wasn't sure if it would be used.
