### ISSUE TITLE
feeds not being published on readthedocs

### ISSUE THREAD

**Issue by mr-c** [abakan/ablog#54]
See https://github.com/rtfd/readthedocs.org/issues/1771

**Comment by abakan** [comment]
I see feeds here: http://mrc.commonwl.org/en/latest/blog/tag/announcement.html
Did you resolve the issue?

**Comment by mr-c** [comment]
Hello @abakan 

Based upon https://github.com/abakan/ablog/blob/devel/ablog/templates/page.html#L6 I expect to see links to the feed in my headers

**Comment by abakan** [comment]
Now I see the issue. I will check that today.

**Comment by abakan** [comment]
Links to feeds should now be included in header. I need to do some more changes though to make sure link to archive feeds is given in archive pages.

**Comment by mr-c** [comment]
Hmm.. I updated my requirements.txt to pull your changes in but I'm not seeing the fix on RTD:

https://readthedocs.org/projects/mrc-snippets/builds/3424079/
http://mrc.commonwl.org/en/latest/

**Comment by abakan** [comment]
It looks like ablog was not reinstalled:
```
  Requirement already satisfied (use --upgrade to upgrade): ablog==0.8.0 from https://github.com/abakan/ablog/archive/28e7f0e64347bca6da1a2523d412ae0af262ecf3.zip in /home/docs/checkouts/readthedocs.org/user_builds/mrc-snippets/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 1))
```
You could try wiping latest from `Project -> Versions`.

**Comment by mr-c** [comment]
Hmm.. Okay, I've wiped `latest` but I get the same result
https://readthedocs.org/projects/mrc-snippets/builds/3424979/

**Comment by abakan** [comment]
I made a release, you should have feeds linked now. I don't know why it still didn't work on RTD after wiping. Maybe they preinstall a version of ablog, and unless version changes you cannot get it reinstalled.

**Comment by mr-c** [comment]
Thank you @abakan , that worked.

Perhaps it is because I didn't check the 'use virtualenv' box?

**Comment by abakan** [comment]
Not sure, I have the hardest time troubleshooting things on RTD.
