### ISSUE TITLE
update:: directive date handling anomaly

### ISSUE THREAD

**Issue by tl-aiyor** [abakan/ablog#58]
When adding ..update:: directive in a post using the date format as per defined in conf.py, e.g.,

	.. update:: Dec 04, 2015
		Added snapshots performance benchmark and analysis :ref:`sec-behaviour-of-vsan-vm-snapshots`.

ablog produced the following errors (note that this only occurs if I add `..update::` directive.  The same date format works without issue under `..post::` directive), 

		Running Sphinx v1.3.3
		Initializing Basicstrap theme directives
		loading pickled environment... not yet created
		building [mo]: targets for 0 po files that are out of date
		building [dirhtml]: targets for 14 source files that are out of date
		updating environment: 14 added, 0 changed, 0 removed
		reading sources... [100%] vmware-snapshot-overview
		Exception occurred:
		  File "/home/lxcuser/sphinx-doc/lib/python3.4/site-packages/ablog/post.py", line 187, in _get_update_dates
			(update_node['date'], docname, post_date_format))
		ValueError: invalid post update date (Dec 04, 2015
		Added snapshots performance benchmark and analysis :ref:`sec-behaviour-of-vsan-vm-snapshots`.) in vmware-snapshot-overview. Expected format: %b %d, %Y
		The full traceback has been saved in /tmp/sphinx-err-hsqqb2_s.log, if you want to report the issue to the developers.
		Please also report this if it was a user error, so that a better error message can be provided next time.
		A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Attached is the actual error log produced by Sphinx
[error.txt](https://github.com/abakan/ablog/files/77803/error.txt)

**Comment by abakan** [comment]
I revised update date parsing. You could get the fixes with `pip install https://github.com/abakan/ablog/archive/devel.zip`. Let me know if the issue persists.

**Comment by tl-aiyor** [comment]
Thanks Ahmet. Confirmed that it's fixed now.
